language: python

python:
    - 2.7

env: 
    - STACKTODOS_MYSQL_DB_HOST=localhost STACKTODOS_MYSQL_DB_PORT=3306 STACKTODOS_MYSQL_DB_USERNAME=root STACKTODOS_MYSQL_DB_PASSWORD="" STACKTODOS_DEVELOPMENT_ENVIRONMENT="True" STACKTODOS_SOCIAL_FACEBOOK_KEY="" STACKTODOS_SOCIAL_FACEBOOK_SECRET="" 

services: mysql

install:
    - pip install --allow-external mysql-connector-python -r requirements.txt
    - pip install coveralls

before_script:
    - mysql -u root -e 'create database stacktodos'
    - alembic -c migrations/alembic.ini upgrade head

script:
    - nosetests --with-coverage --cover-package=app

after_success:
    - coveralls
