language: python
python:
  - "2.7"
env: 
  - "STACKTODOS_MYSQL_DB_HOST=localhost"
  - "STACKTODOS_MYSQL_DB_PORT=localhost"
  - "STACKTODOS_MYSQL_DB_USERNAME=stacktodos"
  - "STACKTODOS_MYSQL_DB_PASSWORD=stacktodos"
services: mysql
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
before-script: python . db upgrade
script: nosetests
