"""empty message

Revision ID: 182ea06ca2b0
Revises: 33a14bcfbe89
Create Date: 2014-04-27 16:29:28.770723

"""

# revision identifiers, used by Alembic.
revision = '182ea06ca2b0'
down_revision = '33a14bcfbe89'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_todo_association')
    op.drop_table('tag')
    op.create_unique_constraint('owner_order_trash', 'todo', ['owner_user_id', 'order', 'in_trash'])
    op.drop_constraint(u'password', 'user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'password', 'user', ['password'])
    op.drop_constraint('owner_order_trash', 'todo')
    op.create_table('tag',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(charset=u'utf8', length=80), nullable=False),
    sa.Column('owner_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], [u'user.id'], name=u'tag_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('tag_todo_association',
    sa.Column('todo_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], [u'tag.id'], name=u'tag_todo_association_ibfk_1'),
    sa.ForeignKeyConstraint(['todo_id'], [u'todo.id'], name=u'tag_todo_association_ibfk_2'),
    sa.PrimaryKeyConstraint('todo_id', 'tag_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
