"""empty message

Revision ID: 243bf89a409a
Revises: 6d1e899f2e5
Create Date: 2014-06-19 11:19:20.195769

"""

# revision identifiers, used by Alembic.
revision = '243bf89a409a'
down_revision = '6d1e899f2e5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('consumed_clock', sa.Integer(), nullable=False))
    op.drop_column('todo', 'remained_clock')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('remained_clock', mysql.INTEGER(display_width=11), nullable=False))
    op.drop_column('todo', 'consumed_clock')
    ### end Alembic commands ###
