"""empty message

Revision ID: 6d1e899f2e5
Revises: d2f0dfcaf27
Create Date: 2014-06-19 10:02:56.453255

"""

# revision identifiers, used by Alembic.
revision = '6d1e899f2e5'
down_revision = 'd2f0dfcaf27'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('extended_clock', sa.Integer(), nullable=False))
    op.add_column('todo', sa.Column('remained_clock', sa.Integer(), nullable=False))
    op.add_column('todo', sa.Column('required_clock', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'required_clock')
    op.drop_column('todo', 'remained_clock')
    op.drop_column('todo', 'extended_clock')
    ### end Alembic commands ###
